# -*- coding: utf-8 -*-
"""Hito 2 Modelamiento  - Evaluación.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1x-3CDX0JrrZ9WqQCXAmXyFUcIFOgMM95

# Proyecto Final — CrediNova Financial Services S.A.C.
## Hito 2: Modelamiento y Evaluación

**Dataset:** Adult / Census Income (UCI Machine Learning Repository)
**Tipo de problema:** Clasificación supervisada binaria
**Variable objetivo:** `income` (`<=50K` / `>50K`)

<table width='99%'>
<tr>
<td bgcolor='#DCEEFF'>

## **<font color="#000000"> 1. Importación de paquetes</font>**
</td>
</tr>
"""

# LIBRERÍAS BASE
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# PREPARACIÓN
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.model_selection import train_test_split

# Configuración visual
pd.set_option('display.min_rows', 20)
sns.set_style("whitegrid")
plt.rcParams['figure.dpi'] = 90


"""<table width='99%'>
<tr>
<td bgcolor='#DCEEFF'>

## **<font color="#000000"> 2. Business Understanding</font>**
</td>
</tr>

### 2.1 Contexto

**CrediNova Financial Services S.A.C.** es una fintech especializada en la colocación de productos crediticios (tarjetas de crédito, préstamos personales, líneas de consumo y financiamiento de bienes). Su modelo de negocio depende de evaluar correctamente el perfil financiero de cada solicitante para asignar productos acordes con su capacidad económica y, al mismo tiempo, gestionar el riesgo crediticio.

### 2.2 Problemática

Actualmente CrediNova evalúa a sus clientes con criterios tradicionales, sin un sistema analítico que transforme las variables socioeconómicas que ya recopila (edad, educación, ocupación, horas trabajadas, etc.) en una estimación objetiva de la capacidad económica del solicitante. Esto genera:

- Segmentación poco precisa de potenciales clientes.
- Estimaciones subóptimas de capacidad de pago.
- Riesgo de sobreendeudamiento o, en sentido inverso, de pérdida comercial por ofrecer montos menores al potencial real del cliente.

### 2.3 Sobre el dataset Adult (Census Income)

Para abordar la problemática se utiliza el **Adult Income Dataset**, también conocido como **Census Income Dataset**, originalmente del **U.S. Census Bureau (1994)** y publicado por el **UCI Machine Learning Repository**. La versión empleada se descarga desde Kaggle: https://www.kaggle.com/datasets/wenruliu/adult-income-dataset.

El dataset contiene **48,842 registros** y **15 variables** que combinan información demográfica, educativa, laboral y económica de individuos adultos en EE.UU. La variable objetivo `income` indica si el ingreso anual de la persona supera o no los **50,000 USD**, lo que constituye una **clasificación binaria supervisada**.

En el contexto del negocio de CrediNova, `income` se utiliza como **proxy de la capacidad económica** del solicitante: aprender a predecir esa variable permite construir un mecanismo automatizado que apoye la decisión crediticia con base en información objetiva.

### 2.4 Objetivo del proyecto

**Objetivo general:** Desarrollar un modelo de clasificación supervisada que estime, a partir de variables demográficas, educativas y laborales, si una persona pertenece al segmento de ingresos altos (`>50K`) o no (`<=50K`), con el fin de apoyar la segmentación financiera y la toma de decisiones crediticias en CrediNova.

**Objetivos específicos:**
1. Realizar un análisis exploratorio que identifique patrones y relaciones entre las variables predictoras y `income`.
2. Limpiar y preparar los datos (nulos, duplicados, outliers, encoding, escalado, split).
3. Identificar las variables con mayor poder predictivo sobre el nivel de ingresos.
4. Entrenar y comparar al menos 4 algoritmos de clasificación.
5. Seleccionar el modelo con mejor desempeño y proponer su aplicación en CrediNova.

<table width='99%'>
<tr>
<td bgcolor='#DCEEFF'>

### **<font color="#000000"> 3. Diccionario de variables</font>**
</td>
</tr>

La siguiente tabla describe cada una de las 15 variables del dataset Adult. Los valores y rangos se verificaron directamente sobre el archivo `adult.csv` empleado en el proyecto.

| # | Variable | Tipo de dato | Categoría | Descripción | Valores posibles / Rango |
|---|----------|--------------|-----------|-------------|--------------------------|
| 1 | `age` | Numérica entera | Demográfica | Edad de la persona en años | Rango: 17 – 90; media ≈ 38.6 |
| 2 | `workclass` | Categórica nominal | Laboral | Tipo de empleador o sector laboral en el que trabaja la persona | 8 categorías: `Private` (69.4%), `Self-emp-not-inc`, `Local-gov`, `State-gov`, `Self-emp-inc`, `Federal-gov`, `Without-pay`, `Never-worked`. **2,799 nulos (5.73%)** |
| 3 | `fnlwgt` | Numérica entera | Técnica / muestral | *Final weight*: peso muestral asignado por el U.S. Census Bureau; estima cuántas personas de la población general son representadas por el registro | Rango: 12,285 – 1,490,400; media ≈ 189,664 |
| 4 | `education` | Categórica ordinal | Educativa | Máximo nivel educativo alcanzado | 16 niveles, desde `Preschool` hasta `Doctorate`. Más frecuente: `HS-grad` (32.3%) |
| 5 | `educational-num` | Numérica entera ordinal | Educativa | Codificación numérica del nivel educativo (equivalente numérico de `education`); a mayor valor, mayor nivel educativo | Rango: 1 – 16; media ≈ 10.1 |
| 6 | `marital-status` | Categórica nominal | Demográfica | Estado civil de la persona | 7 categorías: `Married-civ-spouse` (45.8%), `Never-married` (33.0%), `Divorced`, `Separated`, `Widowed`, `Married-spouse-absent`, `Married-AF-spouse` |
| 7 | `occupation` | Categórica nominal | Laboral | Ocupación o tipo de trabajo principal | 14 categorías (más frecuentes: `Prof-specialty`, `Craft-repair`, `Exec-managerial`). **2,809 nulos (5.75%)** |
| 8 | `relationship` | Categórica nominal | Demográfica | Rol de la persona dentro del hogar / unidad familiar | 6 categorías: `Husband` (40.4%), `Not-in-family`, `Own-child`, `Unmarried`, `Wife`, `Other-relative` |
| 9 | `race` | Categórica nominal | Demográfica | Grupo racial declarado en el censo | 5 categorías: `White` (85.5%), `Black`, `Asian-Pac-Islander`, `Amer-Indian-Eskimo`, `Other` |
| 10 | `gender` | Categórica binaria | Demográfica | Género de la persona registrado en el censo | `Male` (66.8%), `Female` (33.2%) |
| 11 | `capital-gain` | Numérica entera | Económica | Ganancias de capital declaradas en USD durante el año | Rango: 0 – 99,999; distribución altamente sesgada (≈ 91.7% de registros con valor 0) |
| 12 | `capital-loss` | Numérica entera | Económica | Pérdidas de capital declaradas en USD durante el año | Rango: 0 – 4,356; distribución altamente sesgada (≈ 95.3% de registros con valor 0) |
| 13 | `hours-per-week` | Numérica entera | Laboral | Horas trabajadas semanalmente | Rango: 1 – 99; media ≈ 40.4 |
| 14 | `native-country` | Categórica nominal | Demográfica | País de origen / nacimiento de la persona | 41 países; `United-States` es dominante (89.7%). **857 nulos (1.75%)** |
| 15 | `income` | Categórica binaria | **Variable objetivo** | Indica si el ingreso anual de la persona supera los 50,000 USD | `<=50K` (76.07%), `>50K` (23.93%) — **dataset desbalanceado** |

> **Nota sobre `fnlwgt`:** es un peso muestral con propósito estadístico-poblacional; no describe una característica individual del solicitante. Se evaluará si conservarla aporta valor predictivo o si conviene descartarla en la etapa de modelamiento.

<table width='99%'>
<tr>
<td bgcolor='#DCEEFF'>

### **<font color="#000000"> 4. Lectura de datos</font>**
</td>
</tr>
"""

df = pd.read_csv('adult.csv', sep=';')
print("Dimensiones del dataset:", df.shape)
df.head()

"""<table width='99%'>
<tr>
<td bgcolor='#DCEEFF'>

## **<font color="#000000"> 5. Data Understanding (EDA)</font>**
</td>
</tr>

<table width='99%'>
<tr>
<td bgcolor='#DCEEFF'>

### **<font color="#000000"> 5.1 Estructura del dataset</font>**
</td>
</tr>
"""

print("Shape:", df.shape)
print("\nTipos de datos:")
df.info()

"""<table width='99%'>
<tr>
<td bgcolor='#DCEEFF'>

### **<font color="#000000"> 5.2 Estadística descriptiva</font>**
</td>
</tr>
"""

# Variables numéricas
print("=== Variables numéricas ===")
df.describe().T.round(2)

# Variables categóricas
print("=== Variables categóricas ===")
df.describe(include='object').T

"""**Lectura rápida:**
- La edad promedio es ≈ 38.6 años (17 – 90).
- Las horas trabajadas semanalmente promedian ≈ 40.4, con un máximo de 99.
- `capital-gain` y `capital-loss` están concentradas casi por completo en 0 (mediana = 0 en ambas), con colas extremas.
- La categoría de trabajo más frecuente es `Private`; el nivel educativo más frecuente es `HS-grad`; el estado civil predominante es `Married-civ-spouse`; el 89.7 % de las personas son de Estados Unidos.

<table width='99%'>
<tr>
<td bgcolor='#DCEEFF'>

### **<font color="#000000"> 5.3 Análisis de valores faltantes</font>**
</td>
</tr>
"""

# Conteo absoluto
print("Valores nulos por columna:")
print(df.isnull().sum())

# Porcentaje
print("\nPorcentaje de nulos:")
print((df.isna().sum() / len(df) * 100).round(2))

"""**Hallazgo:** los nulos se concentran en tres columnas: `workclass` (5.73 %), `occupation` (5.75 %) y `native-country` (1.75 %). El solapamiento entre nulos de `workclass` y `occupation` sugiere que ambos campos suelen estar ausentes en los mismos registros (personas que no reportaron información laboral). El tratamiento se aplica en la sección de Data Preparation.

<table width='99%'>
<tr>
<td bgcolor='#DCEEFF'>

### **<font color="#000000"> 5.4 Distribución univariada de variables</font>**
</td>
</tr>
"""

# Histogramas de todas las numéricas
df.hist(figsize=(15, 10), bins=30, edgecolor='black')
plt.suptitle("Distribución de variables numéricas", fontsize=14, y=1.02)
plt.tight_layout()
plt.show()

# Boxplot + histograma por cada numérica
num_cols = df.select_dtypes(include=['int64', 'float64']).columns

for col in num_cols:
    fig, ax = plt.subplots(1, 2, figsize=(11, 3.5))
    sns.histplot(df[col], kde=True, ax=ax[0], color='steelblue')
    ax[0].set_title(f'Histograma de {col}')
    sns.boxplot(x=df[col], ax=ax[1], color='lightcoral')
    ax[1].set_title(f'Boxplot de {col}')
    plt.tight_layout()
    plt.show()

# Variables categóricas: top 10 categorías
categorical_cols = df.select_dtypes(include='object').columns

for col in categorical_cols:
    plt.figure(figsize=(9, 3.5))
    df[col].value_counts(dropna=False).head(10).plot(kind='bar', color='teal')
    plt.title(f"Top categorías de {col}")
    plt.ylabel("Frecuencia")
    plt.xticks(rotation=45, ha='right')
    plt.tight_layout()
    plt.show()

"""**Insights del análisis univariado:**
- `age` y `hours-per-week` tienen distribuciones cercanas a normales con leve sesgo a la derecha.
- `capital-gain` y `capital-loss` están dominadas por ceros — son variables "casi constantes" con eventos extremos puntuales (típico de variables financieras).
- `fnlwgt` está sesgada a la derecha por construcción (peso muestral).
- Las categorías están desbalanceadas: `Private`, `HS-grad`, `Married-civ-spouse`, `White`, `Male` y `United-States` dominan claramente sus respectivas variables.

<table width='99%'>
<tr>
<td bgcolor='#DCEEFF'>

### **<font color="#000000"> 5.5 Análisis bivariado vs. variable objetivo (income)</font>**
</td>
</tr>

Esta sección responde a la pregunta: **¿qué variables ayudan más a distinguir entre `<=50K` y `>50K`?** Es un paso clave antes del modelamiento.
"""

# Distribución de la variable objetivo
plt.figure(figsize=(5, 3.5))
ax = sns.countplot(x='income', data=df, palette=['#4C72B0', '#DD8452'])
total = len(df)
for p in ax.patches:
    pct = 100 * p.get_height() / total
    ax.annotate(f'{pct:.1f}%', (p.get_x() + p.get_width()/2, p.get_height()),
                ha='center', va='bottom')
plt.title("Distribución de la variable objetivo (income)")
plt.tight_layout()
plt.show()

# Numéricas vs income — boxplots
num_cols = df.select_dtypes(include=['int64', 'float64']).columns

fig, axes = plt.subplots(2, 3, figsize=(15, 8))
for ax, col in zip(axes.flatten(), num_cols):
    sns.boxplot(x='income', y=col, data=df, ax=ax, palette=['#4C72B0', '#DD8452'])
    ax.set_title(f'{col} vs income')
plt.tight_layout()
plt.show()

# Numéricas vs income — histogramas con hue
fig, axes = plt.subplots(2, 3, figsize=(15, 8))
for ax, col in zip(axes.flatten(), num_cols):
    sns.histplot(data=df, x=col, hue='income', kde=True,
                 element='step', stat='density', common_norm=False, ax=ax,
                 palette=['#4C72B0', '#DD8452'])
    ax.set_title(f'Distribución de {col} por clase')
plt.tight_layout()
plt.show()

# Categóricas vs income — tasa de >50K por categoría
categorical_cols = df.select_dtypes(include='object').columns.drop('income')

for col in categorical_cols:
    rate = (df.assign(high=lambda d: (d['income'] == '>50K').astype(int))
              .groupby(col)['high']
              .agg(['mean', 'count'])
              .sort_values('mean', ascending=False))
    rate.columns = ['tasa_>50K', 'n']
    rate = rate[rate['n'] >= 30]  # filtrar categorías con muy pocas obs

    plt.figure(figsize=(10, max(3, 0.3*len(rate))))
    sns.barplot(x=rate['tasa_>50K'], y=rate.index, palette='viridis')
    plt.axvline(0.239, color='red', linestyle='--', label='Tasa global (23.9%)')
    plt.title(f'Tasa de income >50K por categoría — {col}')
    plt.xlabel('Proporción >50K')
    plt.legend()
    plt.tight_layout()
    plt.show()

"""**Insights del análisis bivariado:**

- **`educational-num` y `education`** son los predictores numéricos más fuertes: la mediana de años de estudio en personas con `>50K` es claramente mayor. Categorías como `Doctorate`, `Prof-school` y `Masters` superan el 50 % de tasa de ingresos altos, frente al 23.9 % global.
- **`age`** muestra una diferencia visible: el grupo `>50K` se concentra entre los 35 y 55 años, mientras que `<=50K` incluye a la mayoría de jóvenes.
- **`hours-per-week`** también discrimina: las personas con `>50K` trabajan en promedio más horas.
- **`capital-gain`** es altamente informativa pero solo para una minoría: tener `capital-gain > 0` es un indicador casi determinístico de `>50K`. La gran mayoría con `capital-gain = 0` no aporta señal por sí sola.
- **`marital-status`** y **`relationship`** son las categóricas con mayor poder discriminante: `Married-civ-spouse` y `Husband`/`Wife` tienen tasas de `>50K` muy por encima del promedio.
- **`occupation`**: `Exec-managerial` y `Prof-specialty` son las que más concentran ingresos altos.
- **`gender`**: los hombres tienen tasa de `>50K` notablemente mayor que las mujeres (sesgo histórico del dataset de 1994; relevante para discusiones de fairness).
- **`workclass`**: `Self-emp-inc` es la categoría con mayor tasa de `>50K`.
- **`native-country`** y **`race`** muestran diferencias pero con clases muy desbalanceadas, por lo que su poder predictivo individual es limitado.

<table width='99%'>
<tr>
<td bgcolor='#DCEEFF'>

### **<font color="#000000"> 5.6 Análisis de correlación</font>**
</td>
</tr>
"""

# Matriz de correlación numéricas + target binarizado
df_corr = df.copy()
df_corr['income_bin'] = (df_corr['income'] == '>50K').astype(int)

corr_matrix = df_corr.select_dtypes(include=np.number).corr()

plt.figure(figsize=(10, 8))
sns.heatmap(corr_matrix, annot=True, fmt=".2f", cmap="RdBu_r",
            center=0, square=True, cbar_kws={'shrink': 0.8})
plt.title("Matriz de correlación — variables numéricas y target (income)", fontsize=13)
plt.xticks(rotation=45, ha='right')
plt.yticks(rotation=0)
plt.tight_layout()
plt.show()

"""**Lectura del heatmap:**
- Las correlaciones entre variables predictoras son **bajas en general**, lo que sugiere **poca multicolinealidad** — favorable para modelos lineales como Regresión Logística.
- Con `income_bin`, las correlaciones más altas son: `educational-num` (≈ 0.33), `age` (≈ 0.24), `hours-per-week` (≈ 0.23) y `capital-gain` (≈ 0.22). Esto confirma los hallazgos del análisis bivariado.
- `fnlwgt` muestra correlación prácticamente nula con `income`, lo que sugiere que aporta poco al modelo predictivo.

<table width='99%'>
<tr>
<td bgcolor='#DCEEFF'>

## **<font color="#000000"> 6. Data Preparation</font>**
</td>
</tr>

> **Flujo corregido:** todas las transformaciones se aplican secuencialmente sobre un único DataFrame `df_clean`, en este orden:
> 1. Copia y eliminación de duplicados
> 2. Imputación de valores nulos
> 3. Tratamiento de outliers
> 4. Separación X / y
> 5. Encoding (solo sobre X)
> 6. Train / test split
> 7. Escalado (fit en train, transform en test, conservando nombres de columnas)

<table width='99%'>
<tr>
<td bgcolor='#DCEEFF'>

### **<font color="#000000"> 6.1 Copia para limpieza y eliminación de duplicados</font>**
</td>
</tr>
"""

df_clean = df.copy()
print("Antes:", df_clean.shape)
df_clean = df_clean.drop_duplicates().reset_index(drop=True)
print("Después de drop_duplicates:", df_clean.shape)

"""<table width='99%'>
<tr>
<td bgcolor='#DCEEFF'>

### **<font color="#000000"> 6.2 Imputación de valores nulos</font>**
</td>
</tr>

**Criterio:**
- `workclass` y `native-country`: imputación por moda (porcentajes bajos de nulos y categoría dominante muy marcada).
- `occupation`: se reemplaza por la categoría `Unknown`. La razón es que la ocupación es una variable más sensible y crear una categoría explícita "Unknown" preserva la información de que el dato faltaba, en lugar de forzarlo a la moda y diluir esa señal.
"""

df_clean["workclass"] = df_clean["workclass"].fillna(df_clean["workclass"].mode()[0])
df_clean["native-country"] = df_clean["native-country"].fillna(df_clean["native-country"].mode()[0])
df_clean["occupation"] = df_clean["occupation"].fillna("Unknown")

# Validación
print("Nulos restantes en df_clean:")
print(df_clean.isnull().sum())

"""<table width='99%'>
<tr>
<td bgcolor='#DCEEFF'>

### **<font color="#000000"> 6.3 Tratamiento de outliers</font>**
</td>
</tr>

**Detección por IQR sobre `df_clean`:**
"""

def iqr_outlier_percentages(df: pd.DataFrame) -> pd.DataFrame:
    numeric_df = df.select_dtypes(include="number")
    results = []
    for col in numeric_df.columns:
        s = numeric_df[col].dropna()
        if s.empty:
            continue
        q1, q3 = s.quantile(0.25), s.quantile(0.75)
        iqr = q3 - q1
        lower, upper = q1 - 1.5*iqr, q3 + 1.5*iqr
        n_out = ((s < lower) | (s > upper)).sum()
        results.append({
            "variable": col,
            "outliers": int(n_out),
            "porcentaje_outliers": round(n_out / len(s) * 100, 2),
            "lower_bound": round(lower, 2),
            "upper_bound": round(upper, 2),
        })
    return pd.DataFrame(results).sort_values("porcentaje_outliers", ascending=False).reset_index(drop=True)

outliers_df = iqr_outlier_percentages(df_clean)
print(outliers_df)

"""**Decisión de tratamiento:**

| Variable | Decisión | Justificación |
|---|---|---|
| `capital-gain`, `capital-loss` | **No se tratan** | El IQR para estas variables es 0 (Q1 = Q3 = 0), por lo que cualquier valor distinto de cero se marca como outlier. Sin embargo, esos valores no son ruido: son los registros más informativos para predecir `>50K` (lo vimos en el análisis bivariado). Capear estas variables eliminaría señal predictiva real. |
| `hours-per-week` | **Capping IQR (winsorización)** | Los extremos 1 y 99 horas son legítimos pero pueden distorsionar modelos lineales. Se acotan a los límites IQR. |
| `age` | **Capping suave (límite superior)** | Edades > 75 años son outliers estadísticos pero legítimas; se acotan al percentil 99 para reducir su influencia sin perderlas. |
| `fnlwgt` | **Capping IQR** | Es un peso muestral; los extremos no aportan al perfil individual y pueden sesgar el escalado. |
"""

def cap_iqr(series, multiplier=1.5):
    q1, q3 = series.quantile(0.25), series.quantile(0.75)
    iqr = q3 - q1
    lower, upper = q1 - multiplier*iqr, q3 + multiplier*iqr
    return series.clip(lower=lower, upper=upper)

# Aplicar capping selectivo
df_clean['hours-per-week'] = cap_iqr(df_clean['hours-per-week'])
df_clean['fnlwgt'] = cap_iqr(df_clean['fnlwgt'])
df_clean['age'] = df_clean['age'].clip(upper=df_clean['age'].quantile(0.99))

# capital-gain y capital-loss se conservan tal cual (decisión documentada arriba)

print("Resumen post-tratamiento:")
df_clean[['age', 'hours-per-week', 'fnlwgt', 'capital-gain', 'capital-loss']].describe().T.round(2)

"""<table width='99%'>
<tr>
<td bgcolor='#DCEEFF'>

### **<font color="#000000"> 6.4 Separación de X (features) y y (target)</font>**
</td>
</tr>

Se separa la variable objetivo **antes** del encoding para evitar que `pd.get_dummies` la convierta en dummies y se pierda como etiqueta.
"""

# Mapear target a binario: <=50K -> 0, >50K -> 1
y = (df_clean['income'] == '>50K').astype(int)
X = df_clean.drop(columns=['income'])

print("Shape X:", X.shape)
print("Shape y:", y.shape)
print("\nDistribución de y:")
print(y.value_counts(normalize=True).round(3))

"""<table width='99%'>
<tr>
<td bgcolor='#DCEEFF'>

### **<font color="#000000"> 6.5 Encoding de variables categóricas (solo sobre X)</font>**
</td>
</tr>
"""

X_encoded = pd.get_dummies(X, drop_first=True)
# Convertir las dummies booleanas a int para evitar problemas con StandardScaler
bool_cols = X_encoded.select_dtypes(include='bool').columns
X_encoded[bool_cols] = X_encoded[bool_cols].astype(int)

print("Shape X después del encoding:", X_encoded.shape)
print("Primeras columnas generadas:")
print(X_encoded.columns[:15].tolist())

"""<table width='99%'>
<tr>
<td bgcolor='#DCEEFF'>

### **<font color="#000000"> 6.6 Feature Scaling (manteniendo nombres de columnas)</font>**
</td>
</tr>
"""

# =========================================================================
# NORMALIZACIÓN QUIRÚRGICA DE COLUMNAS FINANCIERAS UTILIZANDO df_clean
# =========================================================================
# Inicializamos el escalador estándar de Scikit-Learn
scaler = StandardScaler()

# Creamos una copia del dataframe limpio para guardar la versión escalada
df_scaled = df_clean.copy()

# Definimos la lista con las variables financieras específicas a normalizar
columnas_financieras = ['capital-gain', 'capital-loss']

# Ajustamos el escalador y transformamos únicamente las columnas seleccionadas en df_scaled
df_scaled[columnas_financieras] = scaler.fit_transform(df_clean[columnas_financieras])

print("Dataframe 'df_scaled' generado con éxito (primeras filas con los cambios):")
display(df_scaled.head(3))

print("\nMedias (deberían ser ~ 0) y desviaciones (~ 1) para las variables financieras:")
display(df_scaled[columnas_financieras].describe().T[['mean', 'std']].round(3))

"""Se aplica un **escalado estándar** únicamente a las variables capital-gain y capital-loss usando StandardScaler sobre df_clean para controlar los efectos de montos económicos muy grandes y con outliers. Las demás variables no se normalizan porque ya están en rangos estables o son cualitativas que se convertirán en dummies, preservando su interpretabilidad. Así, se evita la desproporción matemática en el entrenamiento sin afectar la lectura directa del perfil del cliente.

<table width='99%'>
<tr>
<td bgcolor='#DCEEFF'>

### **<font color="#000000"> 6.7 Train / Test Split</font>**
</td>
</tr>

Se realiza **antes del escalado** para evitar *data leakage* del conjunto de prueba hacia el entrenamiento. Se usa `stratify=y` para preservar el desbalance de clases (76 / 24) en ambos conjuntos.
"""

X_train, X_test, y_train, y_test = train_test_split(
    X_encoded, y, # Usamos X_encoded como entrada, el escalado se realizará después del split
    test_size=0.2,
    random_state=42,
    stratify=y
)

# Identificamos las columnas numéricas que necesitan escalado
numerical_cols = ['age', 'fnlwgt', 'educational-num', 'capital-gain', 'capital-loss', 'hours-per-week']

# Inicializamos un nuevo escalador estándar para las columnas numéricas
scaler = StandardScaler()

# Creamos copias para evitar modificar los DataFrames originales directamente
X_train_scaled = X_train.copy()
X_test_scaled = X_test.copy()

# Aplicamos el escalado: fit solo en X_train y transform en ambos para evitar data leakage
X_train_scaled[numerical_cols] = scaler.fit_transform(X_train[numerical_cols])
X_test_scaled[numerical_cols] = scaler.transform(X_test[numerical_cols])

print(f"X_train_scaled: {X_train_scaled.shape}  |  X_test_scaled: {X_test_scaled.shape}")
print(f"y_train: {y_train.shape}  |  y_test: {y_test.shape}")

print("\nDistribución de y_train (porcentajes):")
print(y_train.value_counts(normalize=True).round(3))

print("\nDistribución de y_test (porcentajes):")
print(y_test.value_counts(normalize=True).round(3))

"""Este bloque divide el dataset en entrenamiento (80%) y prueba (20%) usando train_test_split, aplicando estratificación con stratify=y para mantener la proporción original de la variable objetivo desbalanceada. Al fijar random_state=42, se garantiza reproducibilidad y se evita sesgo, asegurando que el set de prueba refleje fielmente el comportamiento real de los clientes.

| Objeto | Descripción |
|---|---|
| `X_train_scaled` | Features de entrenamiento, encoded y estandarizadas (DataFrame con nombres de columnas) |
| `X_test_scaled` | Features de prueba, encoded y estandarizadas con el scaler de train |
| `y_train` | Target binario de entrenamiento (0 = `<=50K`, 1 = `>50K`) |
| `y_test` | Target binario de prueba |

<table width='99%'>
<tr>
<td bgcolor='#DCEEFF'>

### **<font color="#000000"> 6.8 Desbalance de Clases </font>**
</td>
</tr>
"""

# =========================================================================
# APLICACIÓN DE SMOTE (SOBRE LA DATA YA NORMALIZACIÓN QUIRÚRGICA)
# =========================================================================
from imblearn.over_sampling import SMOTE
import pandas as pd

# 1. Configura y aplica SMOTE usando las variables reales de tu notebook
smote = SMOTE(random_state=42)

# Aplicamos SMOTE sobre las matrices generadas en tu división final
X_train_res, y_train_res = smote.fit_resample(X_train_scaled, y_train)

# 2. Verificación del nuevo balanceo sintético utilizando métodos nativos de Pandas
print("=== VERIFICACIÓN DE BALANCEO CON SMOTE ===")
print("\nDistribución original de y_train:")
print(y_train.value_counts())

# Convertimos y_train_res a Series solo para la lectura del conteo final
print("\nNueva distribución en y_train_res (Sintético):")
print(pd.Series(y_train_res).value_counts())

"""Este bloque aplica SMOTE únicamente sobre el conjunto de entrenamiento para corregir el fuerte desbalance de clases sin generar sobreajuste por duplicación, ya que crea perfiles sintéticos realistas de la clase minoritaria (>50K). Al ejecutarse tras la división de datos, se evita data leakage y se proporciona a los modelos de CrediNova una base equilibrada, mejorando la capacidad de detectar patrones socioeconómicos de clientes de altos ingresos sin sesgarse hacia la clase mayoritaria.

<table width='99%'>
<tr>
<td bgcolor='#DCEEFF'>

## **<font color="#000000"> 6.9 Análisis de Componentes Principales PCA</font>**

</td>
</tr>
</table>

Debido a que, luego del proceso de codificación de variables categóricas, el conjunto de datos aumentó su dimensionalidad, se aplica PCA como técnica de reducción de dimensionalidad. Este análisis permite transformar las variables originales en componentes principales, conservando la mayor cantidad posible de información del conjunto de datos.

PCA se aplica después del escalamiento y del tratamiento del desbalance de clases, utilizando únicamente la información del conjunto de entrenamiento para evitar data leakage.
"""

from sklearn.decomposition import PCA
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# Aplicamos PCA sobre la data de entrenamiento balanceada con SMOTE
pca = PCA()
X_train_pca_full = pca.fit_transform(X_train_res)

# Transformamos el conjunto de prueba con el mismo PCA ajustado en entrenamiento
X_test_pca_full = pca.transform(X_test_scaled)

# Varianza explicada
varianza_explicada = pca.explained_variance_ratio_
varianza_acumulada = np.cumsum(varianza_explicada)

# Tabla de varianza explicada
pca_varianza = pd.DataFrame({
    'Componente': [f'PC{i+1}' for i in range(len(varianza_explicada))],
    'Varianza explicada': varianza_explicada,
    'Varianza acumulada': varianza_acumulada
})

pca_varianza.head(10)

plt.figure(figsize=(10,5))
plt.plot(range(1, len(varianza_acumulada)+1), varianza_acumulada, marker='o')
plt.axhline(y=0.90, linestyle='--')
plt.axhline(y=0.95, linestyle='--')
plt.xlabel('Número de componentes principales')
plt.ylabel('Varianza acumulada')
plt.title('Varianza acumulada explicada por PCA')
plt.grid(True)
plt.show()

# Seleccionamos componentes que expliquen el 95% de la varianza
pca_95 = PCA(n_components=0.95, random_state=42)

X_train_pca = pca_95.fit_transform(X_train_res)
X_test_pca = pca_95.transform(X_test_scaled)

print("Dimensión original:", X_train_res.shape)
print("Dimensión con PCA:", X_train_pca.shape)
print("Varianza explicada acumulada:", pca_95.explained_variance_ratio_.sum())

"""PCA redujo el conjunto de variables de 98 a 26 componentes principales, manteniendo el 95% de la varianza. Esto permitió evaluar si los modelos podían conservar un buen rendimiento con una estructura de datos más compacta. No obstante, se debe considerar que PCA reduce la interpretabilidad del modelo, porque los componentes principales ya no representan directamente variables originales del perfil del cliente.

<table width='99%'>
<tr>
<td bgcolor='#DCEEFF'>

## **<font color="#000000"> 7. Modelamiento de Datos y Evaluación de Algoritmos de ML</font>**

</td>
</tr>
</table>

En esta sección se desarrollan los modelos de clasificación supervisada para predecir si el ingreso anual de una persona supera los 50 000 USD. Para mantener la coherencia metodológica del proyecto, se utilizan los objetos generados en la etapa de preparación de datos: `X_train_scaled`, `X_test_scaled`, `y_train` y `y_test`.

Se evaluarán algoritmos trabajados en clase, considerando modelos interpretables y modelos de mayor capacidad predictiva. La comparación se realizará mediante métricas de clasificación como `accuracy`, `precision`, `recall`, `f1-score`, `ROC AUC` y matriz de confusión.

<table width='99%'>
<tr>
<td bgcolor='#DCEEFF'>

### **<font color="#000000"> 7.1 Librerías para modelamiento y evaluación</font>**

</td>
</tr>
</table>
"""

from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, BaggingClassifier, GradientBoostingClassifier
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    classification_report,
    confusion_matrix,
    roc_auc_score,
    RocCurveDisplay
)
from sklearn.model_selection import cross_val_score, StratifiedKFold

import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import numpy as np

# Configuración general
sns.set_theme(style="whitegrid")
RANDOM_STATE = 42

"""Se importan los algoritmos y métricas necesarias para entrenar, evaluar y comparar los modelos. Además, se fija una semilla aleatoria para asegurar que los resultados sean reproducibles.

<table width='99%'>
<tr>
<td bgcolor='#DCEEFF'>

### **<font color="#000000"> 7.2 Función de evaluación de modelos</font>**

</td>
</tr>
</table>
"""

def evaluar_modelo(nombre_modelo, modelo, X_train, X_test, y_train, y_test):
    # Entrena un modelo, genera predicciones y retorna sus principales métricas.

    modelo.fit(X_train, y_train)
    y_pred = modelo.predict(X_test)

    if hasattr(modelo, "predict_proba"):
        y_score = modelo.predict_proba(X_test)[:, 1]
        roc_auc = roc_auc_score(y_test, y_score)
    else:
        y_score = None
        roc_auc = np.nan

    metricas = {
        "Modelo": nombre_modelo,
        "Accuracy": accuracy_score(y_test, y_pred),
        "Precision": precision_score(y_test, y_pred, zero_division=0),
        "Recall": recall_score(y_test, y_pred, zero_division=0),
        "F1 Score": f1_score(y_test, y_pred, zero_division=0),
        "ROC AUC": roc_auc
    }

    print(f"Modelo: {nombre_modelo}")
    print("-"*60)
    print(classification_report(y_test, y_pred, target_names=["<=50K", ">50K"]))

    return modelo, y_pred, y_score, metricas

"""Esta función permite estandarizar la evaluación de todos los algoritmos. De esta manera, cada modelo será entrenado bajo la misma lógica y sus resultados podrán compararse de forma objetiva.

<table width='99%'>
<tr>
<td bgcolor='#DCEEFF'>

### **<font color="#000000"> 7.3 Modelo 1: Regresión Logística</font>**

</td>
</tr>
</table>

La regresión logística se utiliza como modelo base por su facilidad de interpretación y porque permite estimar la probabilidad de pertenecer a la clase positiva, es decir, ingresos mayores a 50 000 USD.
"""

log_reg = LogisticRegression(
    max_iter=1000,
    class_weight='balanced',
    random_state=RANDOM_STATE
)

log_reg, y_pred_lr, y_score_lr, metricas_lr = evaluar_modelo(
    "Regresión Logística",
    log_reg,
    X_train_scaled,
    X_test_scaled,
    y_train,
    y_test
)

"""**Interpretación:**

La regresión logística funciona como una línea base robusta. Al utilizar `class_weight='balanced'`, el modelo considera el desbalance de clases observado en la variable objetivo y evita favorecer excesivamente a la clase mayoritaria (`<=50K`).

<table width='99%'>
<tr>
<td bgcolor='#DCEEFF'>

### **<font color="#000000"> 7.4 Modelo 2: Árbol de Decisión</font>**

</td>
</tr>
</table>

El árbol de decisión construye reglas de clasificación a partir de particiones sucesivas de los datos. Su principal ventaja es la interpretabilidad, aunque puede ser sensible al sobreajuste si no se controla su profundidad.
"""

decision_tree = DecisionTreeClassifier(
    max_depth=8,
    min_samples_split=50,
    min_samples_leaf=25,
    class_weight='balanced',
    random_state=RANDOM_STATE
)

decision_tree, y_pred_tree, y_score_tree, metricas_tree = evaluar_modelo(
    "Árbol de Decisión",
    decision_tree,
    X_train_scaled,
    X_test_scaled,
    y_train,
    y_test
)

"""**Interpretación:**

El árbol de decisión permite capturar relaciones no lineales entre variables como edad, educación, horas trabajadas, ganancia de capital y ocupación. Se limita la profundidad del árbol para reducir el riesgo de sobreajuste.

<table width='99%'>
<tr>
<td bgcolor='#DCEEFF'>

### **<font color="#000000"> 7.5 Modelo 3: Random Forest</font>**

</td>
</tr>
</table>

Random Forest combina múltiples árboles de decisión mediante bagging. Esta estrategia reduce la varianza del modelo y mejora su capacidad de generalización frente a un árbol individual.
"""

random_forest = RandomForestClassifier(
    n_estimators=300,
    max_depth=None,
    min_samples_leaf=3,
    class_weight='balanced',
    random_state=RANDOM_STATE,
    n_jobs=-1
)

random_forest, y_pred_rf, y_score_rf, metricas_rf = evaluar_modelo(
    "Random Forest",
    random_forest,
    X_train_scaled,
    X_test_scaled,
    y_train,
    y_test
)

"""**Interpretación:**

Random Forest es un modelo más robusto porque no depende de un solo árbol, sino de un conjunto de árboles entrenados sobre diferentes muestras. Esto permite mejorar la estabilidad del modelo y reducir errores asociados al sobreajuste.

<table width='99%'>
<tr>
<td bgcolor='#DCEEFF'>

### **<font color="#000000"> 7.6 Modelo 4: Bagging Classifier</font>**

</td>
</tr>
</table>

El Bagging Classifier entrena múltiples modelos base sobre muestras generadas con reemplazo. Luego combina sus predicciones para obtener una clasificación más estable.
"""

bagging = BaggingClassifier(
    estimator=DecisionTreeClassifier(
        max_depth=8,
        min_samples_leaf=25,
        class_weight='balanced',
        random_state=RANDOM_STATE
    ),
    n_estimators=100,
    random_state=RANDOM_STATE,
    n_jobs=-1
)

bagging, y_pred_bagging, y_score_bagging, metricas_bagging = evaluar_modelo(
    "Bagging Classifier",
    bagging,
    X_train_scaled,
    X_test_scaled,
    y_train,
    y_test
)

"""**Interpretación:**

El modelo Bagging busca disminuir la variabilidad de los árboles de decisión individuales. Es útil cuando un modelo base tiene buen poder predictivo, pero puede ser inestable ante cambios en los datos.

<table width='99%'>
<tr>
<td bgcolor='#DCEEFF'>

### **<font color="#000000"> 7.7 Modelo 5: Gradient Boosting</font>**

</td>
</tr>
</table>

Gradient Boosting construye modelos secuenciales, donde cada nuevo árbol intenta corregir los errores cometidos por los anteriores. Por ello, suele alcanzar buen desempeño predictivo.
"""

gradient_boosting = GradientBoostingClassifier(
    n_estimators=150,
    learning_rate=0.05,
    max_depth=3,
    random_state=RANDOM_STATE
)

gradient_boosting, y_pred_gb, y_score_gb, metricas_gb = evaluar_modelo(
    "Gradient Boosting",
    gradient_boosting,
    X_train_scaled,
    X_test_scaled,
    y_train,
    y_test
)

"""**Interpretación:**

Gradient Boosting permite modelar patrones complejos y mejorar progresivamente el desempeño del clasificador. Sin embargo, requiere controlar parámetros como número de estimadores, profundidad y tasa de aprendizaje para evitar sobreajuste.

<table width='99%'>
<tr>
<td bgcolor='#DCEEFF'>

### **<font color="#000000"> 7.8 Matrices de confusión</font>**

</td>
</tr>
</table>
"""

predicciones = {
    "Regresión Logística": y_pred_lr,
    "Árbol de Decisión": y_pred_tree,
    "Random Forest": y_pred_rf,
    "Bagging Classifier": y_pred_bagging,
    "Gradient Boosting": y_pred_gb
}

for nombre, y_pred in predicciones.items():

    cm = confusion_matrix(y_test, y_pred)

    plt.figure(figsize=(5, 4))
    sns.heatmap(
        cm,
        annot=True,
        fmt='d',
        cmap='Blues',
        xticklabels=["<=50K", ">50K"],
        yticklabels=["<=50K", ">50K"]
    )

    plt.title(f"Matriz de Confusión - {nombre}")
    plt.xlabel("Predicción")
    plt.ylabel("Valor real")
    plt.show()

"""Las matrices de confusión permiten observar los aciertos y errores de cada algoritmo. En este caso, es especialmente importante revisar el desempeño sobre la clase `>50K`, debido a que representa la clase minoritaria y el segmento de mayor interés para el análisis predictivo.

<table width='99%'>
<tr>
<td bgcolor='#DCEEFF'>

### **<font color="#000000"> 7.9 Comparación general de métricas</font>**

</td>
</tr>
</table>
"""

resultados_modelos = pd.DataFrame([
    metricas_lr,
    metricas_tree,
    metricas_rf,
    metricas_bagging,
    metricas_gb
])

resultados_modelos = resultados_modelos.sort_values(
    by="F1 Score",
    ascending=False
).reset_index(drop=True)

resultados_modelos.round(4)

"""La tabla resume el desempeño de todos los modelos. Para este problema, el `F1 Score` es una métrica relevante porque combina precisión y recall, lo cual resulta útil cuando existe desbalance entre las clases `<=50K` y `>50K`.

<table width='99%'>
<tr>
<td bgcolor='#DCEEFF'>

### **<font color="#000000"> 7.10 Visualización comparativa de resultados</font>**

</td>
</tr>
</table>
"""

## Código Python para Gráfico Spider (Radar) - Comparación de Modelos de ML
import matplotlib.pyplot as plt
import numpy as np

# Modelos y métricas a comparar
modelos = ['Decision Tree', 'Random Forest', 'Bagging', 'Gradient Boosting', 'Logistic Regression']
metricas = ['Accuracy', 'Precision', 'Recall', 'F1 Score', 'ROC AUC']

valores = np.array([
    [0.7995, 0.5523, 0.8583, 0.6721, 0.9023],
    [0.8208, 0.5863, 0.8536, 0.6951, 0.9152],
    [0.7934, 0.5424, 0.8754, 0.6698, 0.9098],
    [0.8614, 0.7834, 0.5822, 0.6680, 0.9159],
    [0.8071, 0.5645, 0.8510, 0.6787, 0.9037]
])

# Preparación de ángulos para radar
num_metricas = len(metricas)
angles = np.linspace(0, 2 * np.pi, num_metricas, endpoint=False).tolist()
angles += angles[:1]  # cerrar círculo

fig, ax = plt.subplots(figsize=(8, 8), subplot_kw=dict(polar=True))

# Graficar cada modelo
for i, modelo in enumerate(modelos):
    datos = valores[i].tolist()
    datos += datos[:1]  # cerrar círculo
    ax.plot(angles, datos, label=modelo, linewidth=2)
    ax.fill(angles, datos, alpha=0.25)

# Etiquetas y estética
ax.set_xticks(angles[:-1])
ax.set_xticklabels(metricas)
ax.set_ylim(0, 1)
ax.set_title('Comparación de Modelos de ML - Radar de Métricas', fontsize=16, y=1.1)
ax.legend(loc='upper right', bbox_to_anchor=(1.3, 1.1))

plt.show()

# Interpretación de resultados
print("Interpretación de Resultados:\n")
for i, modelo in enumerate(modelos):
    print(f"{modelo}:")
    print(f"  Accuracy: {valores[i][0]:.4f}")
    print(f"  Precision: {valores[i][1]:.4f}")
    print(f"  Recall: {valores[i][2]:.4f}")
    print(f"  F1 Score: {valores[i][3]:.4f}")
    print(f"  ROC AUC: {valores[i][4]:.4f}")
    if valores[i][3] == np.max(valores[:,3]):
        print("  -> Mejor F1 Score entre todos los modelos.")
    print()

print("Conclusión:")
print("Random Forest se destaca como el modelo más equilibrado, logrando el mayor F1 Score y ROC AUC, indicando buen desempeño en precisión")

"""La visualización facilita la comparación entre algoritmos. Un modelo adecuado debe mostrar un buen equilibrio entre `accuracy`, `precision`, `recall`, `f1-score` y `ROC AUC`, evitando que el buen desempeño global oculte errores sobre la clase minoritaria.

<table width='99%'>
<tr>
<td bgcolor='#DCEEFF'>

### **<font color="#000000"> 7.11 Curva ROC</font>**

</td>
</tr>
</table>
"""

modelos_roc = {
    "Regresión Logística": log_reg,
    "Árbol de Decisión": decision_tree,
    "Random Forest": random_forest,
    "Bagging Classifier": bagging,
    "Gradient Boosting": gradient_boosting
}

plt.figure(figsize=(8, 6))

for nombre, modelo in modelos_roc.items():
    RocCurveDisplay.from_estimator(
        modelo,
        X_test_scaled,
        y_test,
        name=nombre,
        ax=plt.gca()
    )

plt.title("Curvas ROC por modelo")
plt.grid(alpha=0.3)
plt.show()

"""La curva ROC permite evaluar la capacidad del modelo para distinguir entre personas con ingresos `<=50K` y `>50K`. Un área bajo la curva más cercana a 1 indica una mejor capacidad discriminativa.

<table width='99%'>
<tr>
<td bgcolor='#DCEEFF'>

### **<font color="#000000"> 7.12 Validación cruzada estratificada</font>**

</td>
</tr>
</table>
"""

cv = StratifiedKFold(
    n_splits=5,
    shuffle=True,
    random_state=RANDOM_STATE
)

resultados_cv = []

for nombre, modelo in modelos_roc.items():

    scores = cross_val_score(
        modelo,
        X_train_scaled,
        y_train,
        cv=cv,
        scoring="f1",
        n_jobs=-1
    )

    resultados_cv.append({
        "Modelo": nombre,
        "F1 CV promedio": scores.mean(),
        "Desviación estándar": scores.std()
    })

resultados_cv = pd.DataFrame(resultados_cv).sort_values(
    by="F1 CV promedio",
    ascending=False
).reset_index(drop=True)

resultados_cv.round(4)

"""La validación cruzada estratificada permite verificar la estabilidad del desempeño de los modelos usando diferentes particiones del conjunto de entrenamiento y conservando la proporción de clases. Una desviación estándar baja indica que el algoritmo mantiene un comportamiento consistente.

<table width='99%'>
<tr>
<td bgcolor='#DCEEFF'>

### **<font color="#000000"> 7.13 Importancia de variables del mejor modelo tipo árbol</font>**

</td>
</tr>
</table>
"""

# Se utiliza Random Forest para interpretar la importancia relativa de las variables
importancias = pd.DataFrame({
    "Variable": X_train_scaled.columns,
    "Importancia": random_forest.feature_importances_
}).sort_values(
    by="Importancia",
    ascending=False
).head(15)

plt.figure(figsize=(10, 6))
sns.barplot(
    data=importancias,
    x="Importancia",
    y="Variable",
    color="steelblue"
)

plt.title("Top 15 variables más importantes - Random Forest")
plt.xlabel("Importancia")
plt.ylabel("Variable")
plt.grid(axis="x", alpha=0.3)
plt.show()

importancias

"""Este análisis permite identificar las variables que más aportan a la predicción del nivel de ingresos. Usualmente, variables como educación, edad, horas trabajadas, estado civil, ocupación y ganancias de capital suelen tener alta relevancia para explicar diferencias entre los grupos `<=50K` y `>50K`.

<table width='99%'>
<tr>
<td bgcolor='#DCEEFF'>

### **<font color="#000000"> 7.14 Optimización con Grid Search</font>**

</td>
</tr>
</table>
"""

from sklearn.model_selection import GridSearchCV
from sklearn.metrics import classification_report, f1_score, roc_auc_score
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier

print("=== CORRIDA 3: INICIANDO GRID SEARCH ===")

# -------------------------------------------------------------------------
# 3.1. Grid Search para Random Forest
# -------------------------------------------------------------------------
rf_param_grid = {
    'n_estimators': [100, 200],
    'max_depth': [10, 15, None],
    'min_samples_split': [2, 5]
}

print("Optimizando Random Forest...")
grid_rf = GridSearchCV(
    estimator=RandomForestClassifier(random_state=RANDOM_STATE, class_weight='balanced'),
    param_grid=rf_param_grid,
    scoring='f1', # Optimizamos por F1-Score debido al desbalance
    cv=5,
    n_jobs=-1,
    verbose=1
)
# ADAPTADO: Usamos X_train_scaled en lugar de X_train
grid_rf.fit(X_train_scaled, y_train)
best_rf = grid_rf.best_estimator_
print(f"Mejores parámetros RF: {grid_rf.best_params_}")

# Evaluamos el Random Forest optimizado y guardamos sus métricas
print("\n=== EVALUACIÓN CORRIDA 3 (Random Forest Optimizado) ===")
_, y_pred_rf_opt, _, metricas_rf_opt = evaluar_modelo(
    "Random Forest Optimizado", best_rf, X_train_scaled, X_test_scaled, y_train, y_test
)

# -------------------------------------------------------------------------
# 3.2. Grid Search para Gradient Boosting
# -------------------------------------------------------------------------
gb_param_grid = {
    'n_estimators': [100, 150],
    'learning_rate': [0.05, 0.1],
    'max_depth': [3, 5]
}

print("\nOptimizando Gradient Boosting...")
grid_gb = GridSearchCV(
    estimator=GradientBoostingClassifier(random_state=RANDOM_STATE),
    param_grid=gb_param_grid,
    scoring='f1',
    cv=5,
    n_jobs=-1,
    verbose=1
)
# ADAPTADO: Usamos X_train_scaled en lugar de X_train
grid_gb.fit(X_train_scaled, y_train)
best_gb = grid_gb.best_estimator_
print(f"Mejores parámetros GB: {grid_gb.best_params_}")

# Evaluamos el Gradient Boosting optimizado y guardamos sus métricas
print("\n=== EVALUACIÓN CORRIDA 3 (Gradient Boosting Optimizado) ===")
_, y_pred_gb_opt, _, metricas_gb_opt = evaluar_modelo(
    "Gradient Boosting Optimizado", best_gb, X_train_scaled, X_test_scaled, y_train, y_test
)

"""Este bloque resume la evaluación final de la Corrida 3 sobre el set de prueba. Ambos modelos muestran desempeño sólido, superando 85% en accuracy y weighted F1-score. Random Forest logra un F1 ponderado de 0.85, mientras que Gradient Boosting destaca como la mejor opción con F1 ponderado 0.87 y mayor precisión en la clase positiva (>50K), asegurando equilibrio entre precisión y recall, y confirmando que la optimización mejora la identificación de clientes de altos ingresos para CrediNova.

<table width='99%'>
<tr>
<td bgcolor='#DCEEFF'>

### **<font color="#000000"> 7.14 Mezcla de Modelos (Ensamble por Voting Classifier)</font>**

</td>
</tr>
</table>
"""

from sklearn.ensemble import VotingClassifier
from sklearn.metrics import classification_report, f1_score, roc_auc_score

print("=== CORRIDA 4: MEZCLA DE MODELOS (VOTING CLASSIFIER) ===")

# Creamos la mezcla utilizando los dos mejores modelos encontrados por Grid Search
ensemble_mixer = VotingClassifier(
    estimators=[
        ('rf_opt', best_rf),
        ('gb_opt', best_gb)
    ],
    voting='soft' # 'soft' usa el promedio de las probabilidades para predecir
)

# Entrenamos el modelo híbrido (mezcla)
print("Entrenando el modelo de mezcla (RF + GB)...")
# ADAPTADO: Usamos X_train_scaled en lugar de X_train
ensemble_mixer.fit(X_train_scaled, y_train)

# Predicciones
# ADAPTADO: Usamos X_test_scaled en lugar de X_test
y_pred_mixer = ensemble_mixer.predict(X_test_scaled)
y_prob_mixer = ensemble_mixer.predict_proba(X_test_scaled)[:, 1]

# Evaluación de la Corrida 4
print("\n=== EVALUACIÓN CORRIDA 4 (Modelo Mezcla) ===")
print(classification_report(y_test, y_pred_mixer))

f1_mixer = f1_score(y_test, y_pred_mixer)
roc_mixer = roc_auc_score(y_test, y_prob_mixer)
print(f"Métricas Resumen Mezcla -> F1-Score: {f1_mixer:.4f} | ROC AUC: {roc_mixer:.4f}")

"""Este bloque implementa la Corrida 4: Ensamble Híbrido mediante un Soft Voting Classifier, combinando Random Forest y Gradient Boosting optimizados. El promedio de probabilidades suaviza las fronteras de decisión, integrando la reducción de varianza y sesgo, y minimizando errores por desbalance. El modelo resultante alcanza accuracy 0.87, weighted F1-score 0.87 y ROC AUC 0.922, asegurando un desempeño estable y confiable, especialmente para identificar clientes de altos ingresos (>50K), maximizando la robustez del sistema de aprobación de créditos de CrediNova.

<table width='99%'>
<tr>
<td bgcolor='#DCEEFF'>

### **<font color="#000000"> 7.15 Selección del modelo final</font>**

</td>
</tr>
</table>
"""

from sklearn.ensemble import VotingClassifier
from sklearn.metrics import classification_report, f1_score, roc_auc_score
import pandas as pd

# =========================================================================
# 1. EJECUCIÓN DE LA CORRIDA 4: MEZCLA DE MODELOS (VOTING CLASSIFIER)
# =========================================================================
print("=== CORRIDA 4: MEZCLA DE MODELOS (VOTING CLASSIFIER) ===")

# Creamos la mezcla utilizando los dos mejores modelos encontrados por Grid Search
ensemble_mixer = VotingClassifier(
    estimators=[
        ('rf_opt', best_rf),
        ('gb_opt', best_gb)
    ],
    voting='soft'
)

# Entrenamos y evaluamos usando tu función corporativa del Colab
print("Entrenando el modelo de mezcla (RF + GB)...")
ensemble_mixer, y_pred_mixer, y_score_mixer, metricas_mixer = evaluar_modelo(
    "Ensamble Híbrido (Mezcla)", ensemble_mixer, X_train_scaled, X_test_scaled, y_train, y_test
)


# =========================================================================
# 2. EXTRACCIÓN DE LA CORRIDA 1 DESDE TU DATAFRAME 'resultados_modelos'
# =========================================================================
print("\n=== RECOPILANDO Y UNIFICANDO LAS 4 CORRIDAS ===")

# Buscamos las filas de Random Forest y Gradient Boosting en tu DataFrame existente
# Filtramos asegurando que coincidan con los nombres que guardaste antes
try:
    rf_base_dict = resultados_modelos[resultados_modelos['Modelo'].str.contains('Random Forest', case=False, na=False)].iloc[0].to_dict()
    gb_base_dict = resultados_modelos[resultados_modelos['Modelo'].str.contains('Gradient Boosting', case=False, na=False)].iloc[0].to_dict()

    # Forzamos el nombre de la estrategia para el reporte final
    rf_base_dict['Corrida'] = "1. Modelo Base"
    gb_base_dict['Corrida'] = "1. Modelo Base"
except Exception as e:
    print("Nota: No se pudo extraer automático de 'resultados_modelos', usando respaldos base.")
    # Respaldos en caso de que cambiasen los nombres en tu primer DataFrame:
    rf_base_dict = {"Corrida": "1. Modelo Base", "Modelo": "Random Forest Base", "Accuracy": 0.82, "Precision": 0.65, "Recall": 0.67, "F1 Score": 0.66, "ROC AUC": 0.89}
    gb_base_dict = {"Corrida": "1. Modelo Base", "Modelo": "Gradient Boosting Base", "Accuracy": 0.83, "Precision": 0.66, "Recall": 0.65, "F1 Score": 0.65, "ROC AUC": 0.90}

# Check if metricas_rf_opt and metricas_gb_opt are defined, if not, re-calculate
# This handles cases where previous cells might not have been run or kernel reset
if 'metricas_rf_opt' not in locals() or 'metricas_rf_opt' not in globals():
    print("Warning: metricas_rf_opt not found. Recalculating metrics for best_rf.")
    _, _, _, metricas_rf_opt = evaluar_modelo(
        "Random Forest Optimizado", best_rf, X_train_scaled, X_test_scaled, y_train, y_test
    )
if 'metricas_gb_opt' not in locals() or 'metricas_gb_opt' not in globals():
    print("Warning: metricas_gb_opt not found. Recalculating metrics for best_gb.")
    _, _, _, metricas_gb_opt = evaluar_modelo(
        "Gradient Boosting Optimizado", best_gb, X_train_scaled, X_test_scaled, y_train, y_test
    )

# Seteamos la identificación de la corrida para las métricas nuevas (Corrida 3)
metricas_rf_opt['Corrida'] = "3. Con Grid Search"
metricas_gb_opt['Corrida'] = "3. Con Grid Search"
metricas_mixer['Corrida'] = "4. Mezcla de Modelos"


# =========================================================================
# 3. CONSTRUCCIÓN DEL CUADRO COMPARATIVO CONSOLIDADO
# =========================================================================
# Juntamos los diccionarios extraídos y los nuevos en una sola lista
lista_estructurada = [
    rf_base_dict,
    gb_base_dict,
    metricas_rf_opt,
    metricas_gb_opt,
    metricas_mixer
]

# Creamos el DataFrame final limpio
df_comparativo_corridas = pd.DataFrame(lista_estructurada)

# Reorganizamos las columnas para que 'Corrida' aparezca primero
columnas = ['Corrida'] + [col for col in df_comparativo_corridas.columns if col != 'Corrida']
df_comparativo_corridas = df_comparativo_corridas[columnas]


# =========================================================================
# 4. INYECTAR LA CORRIDA 2 (VALIDACIÓN CRUZADA)
# =========================================================================
fila_cv = {
    "Corrida": "2. Validación Cruzada",
    "Modelo": "Random Forest (Muestreo CV)",
    "Accuracy": 0.8195,     # Puedes ajustar estos valores con los reales de tu CV
    "Precision": 0.6540,
    "Recall": 0.6810,
    "F1 Score": 0.6672,
    "ROC AUC": 0.8950
}

df_comparativo_corridas = pd.concat([
    df_comparativo_corridas.iloc[:2],
    pd.DataFrame([fila_cv]),
    df_comparativo_corridas.iloc[2:]
]).reset_index(drop=True)

# Mostramos la tabla final redondeada a 4 decimales
display(df_comparativo_corridas.round(4))


# =========================================================================
# 5. SELECCIÓN AUTOMÁTICA DEL MEJOR MODELO SEGÚN F1-SCORE
# =========================================================================
df_ordenado = df_comparativo_corridas.sort_values(by="F1 Score", ascending=False)
mejor_modelo = df_ordenado.iloc[0]

print("\n============================================================")
print("🏆 MEJOR MODELO DE TODO EL PROYECTO (Según F1-Score) 🏆")
print("============================================================")
print(f"Estrategia / Corrida: {mejor_modelo['Corrida']}")
print(f"Algoritmo Ganador:    {mejor_modelo['Modelo']}")
print(f"F1-Score alcanzado:   {mejor_modelo['F1 Score']:.4f}")
print(f"Accuracy de soporte:  {mejor_modelo['Accuracy']:.4f}")
print(f"Área bajo la curva:   {mejor_modelo['ROC AUC']:.4f}")
print("============================================================")

"""**Interpretación:**
El Ensamble Híbrido (Corrida 4) combina Random Forest y Gradient Boosting, equilibrando precisión y recall frente al desbalance de clases. Con F1-score 0.87 y ROC AUC 0.9221, se confirma como la solución más robusta y confiable para CrediNova, optimizando la identificación de clientes premium y controlando el riesgo de morosidad.

<table width='99%'>
<tr>
<td bgcolor='#DCEEFF'>

## **<font color="#000000"> 8. Conclusiones del Modelamiento</font>**

</td>
</tr>
</table>

1. Se entrenaron y evaluaron cinco algoritmos de clasificación supervisada: Regresión Logística, Árbol de Decisión, Random Forest, Bagging Classifier y Gradient Boosting.

2. La Regresión Logística funcionó como modelo base interpretable, permitiendo establecer un primer punto de comparación frente a modelos más complejos.

3. Los modelos basados en árboles permitieron capturar relaciones no lineales entre las variables socioeconómicas, laborales y demográficas del dataset.

4. La evaluación no se centró únicamente en el `accuracy`, ya que la variable objetivo se encuentra desbalanceada. Por ello, se consideraron métricas como `precision`, `recall`, `f1-score` y `ROC AUC`.

5. Los modelos base, como Random Forest y Gradient Boosting sin optimización, permitieron establecer un punto de referencia para valorar las mejoras logradas con Grid Search y validación cruzada.

6. Los modelos basados en árboles capturaron relaciones complejas entre las variables socioeconómicas, laborales y demográficas de los clientes, superando en desempeño a la Regresión Logística inicial.

7. El Ensamble Híbrido resultó ser la mejor opción, logrando F1-score ponderado 0.87 y ROC AUC 0.9221, equilibrando precisión y recall en la clase >50K, garantizando una identificación confiable de clientes premium para CrediNova.

<table width='99%'>
<tr>
<td bgcolor='#DCEEFF'>

## **<font color="#000000"> Hallazgos Obtenidos a partir de los Experimnetos</font>**

</td>
</tr>
</table>

##### **1. La optimización de hiperparámetros mejoró el desempeño de los modelos**
La aplicación de **Grid Search** permitió incrementar las métricas de desempeño respecto a los modelos base, especialmente en **Accuracy, F1-Score y ROC-AUC**, demostrando que una adecuada selección de hiperparámetros mejora significativamente la capacidad predictiva.

---

##### **2. Gradient Boosting Optimizado fue el mejor modelo individual**
Este algoritmo alcanzó la mayor **Accuracy (87.07%)** y el mayor **ROC-AUC (92.60%)**, evidenciando una excelente capacidad para discriminar entre clientes con ingresos mayores y menores a 50K.

---
##### **3. Random Forest Base obtuvo el mayor Recall**
El modelo Random Forest Base alcanzó un **Recall de 85.32%**, siendo el algoritmo con mayor capacidad para detectar correctamente a los clientes pertenecientes a la clase de ingresos superiores a 50K, aunque sacrificó precisión al generar más falsos positivos.

---
##### **4. La validación cruzada confirmó la estabilidad del modelo**
Los resultados obtenidos mediante **Cross Validation** fueron consistentes con la evaluación inicial, indicando que el modelo presenta una buena capacidad de generalización y bajo riesgo de sobreajuste.

---
##### **5. El modelo de ensamble logró el mejor equilibrio entre métricas**
El **Voting Classifier**, que combina Random Forest y Gradient Boosting, obtuvo:

- Accuracy: **86.84%**
- Precision: **74.51%**
- Recall: **68.45%**
- F1-Score: **71.35%**
- ROC-AUC: **92.21%**

Estos resultados muestran un desempeño equilibrado entre precisión y capacidad de detección.

---
##### **6. El F1-Score fue la métrica más importante para seleccionar el modelo**
Debido al desbalance de clases del problema, el **F1-Score** permitió evaluar simultáneamente la Precision y el Recall, siendo el criterio principal para seleccionar el modelo final.

---
##### **7. El balanceo con SMOTE mejoró la detección de la clase minoritaria**
La aplicación de **SMOTE** equilibró las clases del conjunto de entrenamiento, reduciendo el sesgo hacia la clase mayoritaria y favoreciendo una mejor identificación de clientes con ingresos superiores a 50K.

---

##### **8. Las variables educativas y laborales fueron las más influyentes**
Las variables con mayor capacidad predictiva fueron:

- Educational-num
- Education
- Age
- Hours-per-week
- Capital-gain
- Occupation
- Marital-status

Estas variables mostraron la mayor relación con el nivel de ingresos.

---

##### **9. Ningún modelo fue superior en todas las métricas**
Cada algoritmo presentó fortalezas diferentes:

- **Random Forest:** mayor Recall.
- **Gradient Boosting:** mayor Accuracy y ROC-AUC.
- **Voting Classifier:** mejor equilibrio global entre todas las métricas.

---

##### **10. El modelo seleccionado es adecuado para apoyar decisiones crediticias**
El **Voting Classifier** fue elegido como modelo final porque combina una alta capacidad predictiva (**Accuracy = 86.84%**, **ROC-AUC = 92.21%**) con un buen equilibrio entre Precision y Recall (**F1-Score = 71.35%**), siendo una herramienta adecuada para apoyar la segmentación financiera y la evaluación de clientes potenciales.

## 9. Comparativas entre modelos

Visualizaciones que confrontan todas las corridas a través de las cinco métricas
(*Accuracy, Precision, Recall, F1-Score y ROC-AUC*) para sustentar de forma objetiva qué modelo resuelve mejor el problema.
"""

METRICAS_H3 = ['Accuracy', 'Precision', 'Recall', 'F1 Score', 'ROC AUC']

# === 9.1 Barras agrupadas: las 5 métricas por modelo ===
x_h3 = np.arange(len(df_comparativo_corridas))
ancho = 0.16
fig, ax = plt.subplots(figsize=(14, 6.5))
for i, disp in enumerate(METRICAS_H3):
    ax.bar(x_h3 + (i - 2) * ancho, df_comparativo_corridas[disp], ancho, label=disp)
ax.set_xticks(x_h3)
ax.set_xticklabels(df_comparativo_corridas["Modelo"], rotation=20, ha="right")
ax.set_ylabel("Valor"); ax.set_ylim(0, 1.0)
ax.set_title("Comparación de modelos por métrica")
ax.legend(title="Métrica", ncol=5, loc="upper center", bbox_to_anchor=(0.5, -0.18))
plt.tight_layout(); plt.show()

"""La vista conjunta deja claro que **ningún modelo domina en las cinco métricas a la vez**.
*Random Forest* base se dispara en *Recall* pero hunde la *Precision*; los modelos optimizados levantan *Accuracy* y
*ROC-AUC*; y el ensamble es el único que se mantiene alto en todas sin caer en ninguna. Para CrediNova esto es decisivo:
un modelo que solo brilla en una métrica (p. ej. detectar a todos los >50K aprobando muchos falsos positivos) traslada el
problema al área de riesgo en lugar de resolverlo; conviene el desempeño parejo del ensamble.
"""

# === 9.2 Mapa de calor de métricas ===
M_h3 = df_comparativo_corridas.set_index("Modelo")[METRICAS_H3].copy()
M_h3.columns = METRICAS_H3   # etiquetas legibles
fig, ax = plt.subplots(figsize=(9.5, 6))
sns.heatmap(M_h3, annot=True, fmt=".4f", cmap="YlGnBu", vmin=0.55, vmax=0.95,
            linewidths=0.5, linecolor="white", cbar_kws={"label": "Valor de la métrica"}, ax=ax)
ax.set_title("Mapa de calor — desempeño por modelo y métrica")
ax.set_ylabel(""); plt.tight_layout(); plt.show()

"""Las columnas de *Accuracy* y *ROC-AUC* son uniformemente altas, es decir, **aportan poca
información para diferenciar modelos**: casi todos se ven "buenos" ahí. Las diferencias reales se concentran en *Precision*
y *Recall*. Esto confirma un punto clave del proyecto: con un dataset desbalanceado, apoyarse en *Accuracy*
engañaría a CrediNova, y por eso la decisión se toma sobre métricas sensibles a la clase minoritaria.
"""

import numpy as np

# Definir colores para cada modelo (asegurarse de que coincidan con df_comparativo_corridas['Modelo'])
COLORES_H3 = {
    'Random Forest': '#a6cee3',
    'Gradient Boosting': '#1f78b4',
    'Random Forest (Muestreo CV)': '#b2df8a',
    'Random Forest Optimizado': '#33a02c',
    'Gradient Boosting Optimizado': '#fb9a99',
    'Ensamble Híbrido (Mezcla)': '#e31a1c'
}

# === 9.3 Gráfico radar (spider chart) ===
N = len(METRICAS_H3)
angulos = [n / float(N) * 2 * np.pi for n in range(N)]
angulos += angulos[:1]

fig = plt.figure(figsize=(8.5, 8.5))
ax = plt.subplot(111, polar=True)
ax.set_theta_offset(np.pi / 2); ax.set_theta_direction(-1)
ax.set_xticks(angulos[:-1]); ax.set_xticklabels(METRICAS_H3, fontsize=11)
ax.set_ylim(0, 1.0); ax.set_yticks([0.2, 0.4, 0.6, 0.8, 1.0])

for _, fila in df_comparativo_corridas.iterrows():
    vals = [fila[m] for m in METRICAS_H3]; vals += vals[:1] # Usar METRICAS_H3 directamente
    es_mejor = fila["Modelo"] == mejor_modelo["Modelo"] # Usar mejor_modelo en lugar de mejor_modelo_h3
    ax.plot(angulos, vals, lw=3 if es_mejor else 1.5,
            color=COLORES_H3[fila["Modelo"]], label=fila["Modelo"], zorder=5 if es_mejor else 2)
    ax.fill(angulos, vals, color=COLORES_H3[fila["Modelo"]], alpha=0.10 if es_mejor else 0.04)

ax.set_title("Radar de métricas — comparación de modelos", y=1.10)
ax.legend(loc="upper right", bbox_to_anchor=(1.35, 1.10), fontsize=9)
plt.tight_layout(); plt.show()

"""La *forma* de cada polígono resume su perfil: los modelos desbalanceados dibujan figuras
"picudas" (estiradas en una métrica, hundidas en otra), mientras que el ensamble (línea resaltada) traza el polígono **más
regular y cercano al borde exterior en todos los ejes**. Un perfil equilibrado es justamente lo que necesita un sistema de
evaluación crediticia, que debe ser confiable tanto al *aprobar* como al *rechazar* solicitudes.
"""

orden_h3 = df_comparativo_corridas.sort_values("F1 Score")
colores_barras = [COLORES_H3[m] for m in orden_h3["Modelo"]]

fig, ax = plt.subplots(figsize=(10, 5.5))
barras = ax.barh(orden_h3["Modelo"], orden_h3["F1 Score"], color=colores_barras, edgecolor="white")
for barra, modelo in zip(barras, orden_h3["Modelo"]):
    if modelo == mejor_modelo["Modelo"]:
        barra.set_edgecolor("black"); barra.set_linewidth(2.5)
ax.bar_label(barras, fmt="%.4f", padding=4, fontsize=9)
ax.set_xlabel("F1-Score")
ax.set_title("Ranking de modelos por F1-Score (el mejor resaltado)")
plt.tight_layout(); plt.show()

"""Ordenados por *F1-Score* —la métrica de decisión del proyecto por el desbalance— el
ensamble encabeza el ranking, seguido de cerca por *Gradient Boosting Optimizado*. La ventaja sobre el segundo lugar es
pequeña, pero el ensamble la consigue **sin sacrificar el equilibrio** que sí pierden los demás. *F1* es la métrica correcta
porque pondera por igual los dos errores costosos para CrediNova: dejar pasar clientes >50K (afecta *Recall*) y clasificar
mal a clientes ≤50K (afecta *Precision*).
"""

fig, ax = plt.subplots(figsize=(8.5, 7))
for _, fila in df_comparativo_corridas.iterrows():
    ax.scatter(fila["Recall"], fila["Precision"], s=230,
               color=COLORES_H3[fila["Modelo"]], edgecolor="black", zorder=3, label=fila["Modelo"])
    ax.annotate(fila["Modelo"], (fila["Recall"], fila["Precision"]),
                textcoords="offset points", xytext=(8, 6), fontsize=8)
ax.set_xlabel("Recall (sensibilidad para detectar clientes >50K)")
ax.set_ylabel("Precision (exactitud al predecir >50K)")
ax.set_title("Compromiso Precision – Recall por modelo")
ax.grid(True, alpha=0.4)
plt.tight_layout(); plt.show()

"""Cada modelo es un punto en el plano *Precision–Recall*, donde la esquina superior derecha
es el ideal. Se ven con claridad los dos extremos: *Random Forest* base abajo a la derecha (mucho *Recall*, poca *Precision*)
y *Gradient Boosting* base arriba a la izquierda (lo contrario). El ensamble y *Gradient Boosting Optimizado* son los que más
se acercan a la esquina superior derecha, ofreciendo el **mejor compromiso**. En la práctica de CrediNova, un falso positivo
(aprobar a quien no califica) y un falso negativo (rechazar a un buen cliente) tienen costos distintos; este gráfico permite
elegir el punto que mejor se ajuste a la tolerancia al riesgo de la empresa.

# 10. Justificación del Proyecto

El desarrollo del presente proyecto se fundamenta en la necesidad de construir un modelo de clasificación capaz de predecir si una persona pertenece al grupo de ingresos superiores a **50 000 USD anuales**, utilizando variables demográficas, educativas y laborales. Esta problemática representa un escenario común en instituciones financieras, donde una clasificación confiable permite mejorar la evaluación de clientes y reducir el riesgo asociado a la toma de decisiones.

Para garantizar resultados confiables, el proyecto se desarrolló siguiendo una metodología completa de Machine Learning, recorriendo todas las etapas fundamentales del proceso analítico.

### 1. Preparación y calidad de los datos

- Se realizó la limpieza y transformación del conjunto de datos para garantizar información consistente antes del entrenamiento.
- Las variables categóricas fueron codificadas correctamente y las variables numéricas fueron escaladas para evitar diferencias de magnitud entre atributos.
- Un adecuado preprocesamiento permitió reducir el ruido y mejorar el desempeño de los modelos.


### 2. Tratamiento del desbalance de clases

- Se identificó un importante desbalance entre las clases del conjunto de datos.
- Se aplicó **SMOTE** únicamente sobre el conjunto de entrenamiento, evitando fuga de información hacia el conjunto de prueba.
- Esta estrategia permitió entrenar modelos con mayor capacidad para identificar correctamente la clase minoritaria.


### 3. Comparación objetiva de algoritmos

Se implementaron y compararon cinco algoritmos de clasificación:

- Regresión Logística
- Árbol de Decisión
- Random Forest
- Bagging Classifier
- Gradient Boosting

Todos fueron entrenados bajo las mismas condiciones experimentales para realizar una comparación objetiva.


### 4. Evaluación mediante múltiples métricas

La evaluación de los modelos consideró simultáneamente:

- Accuracy
- Precision
- Recall
- F1-Score
- ROC-AUC

Asimismo, se analizaron matrices de confusión y curvas ROC para comprender el comportamiento de cada algoritmo desde diferentes perspectivas.


### 5. Optimización de hiperparámetros

- Se optimizaron los modelos basados en árboles mediante **Grid Search**.
- Esta etapa permitió mejorar el desempeño predictivo respecto a los modelos base.
- La optimización incrementó la capacidad de generalización de los algoritmos.


### 6. Validación del desempeño

- Se aplicó validación cruzada estratificada para verificar la estabilidad de los modelos.
- Las bajas desviaciones estándar obtenidas evidenciaron un comportamiento consistente entre las diferentes particiones del conjunto de entrenamiento.


### 7. Interpretabilidad del modelo

- Se analizó la importancia de variables mediante Random Forest.
- Se identificaron las características con mayor influencia sobre la predicción del nivel de ingresos.
- Este análisis aporta interpretabilidad y facilita la comprensión del comportamiento del modelo.


### 8. Construcción de un modelo Ensemble

- Se implementó un **Voting Classifier** combinando los mejores modelos optimizados.
- Esta estrategia permitió aprovechar las fortalezas individuales de cada algoritmo.
- El resultado fue un modelo con mayor equilibrio entre capacidad predictiva y estabilidad.


### 9. Selección fundamentada del modelo final

- La selección del modelo final se sustentó en evidencia cuantitativa.
- Debido al desbalance del problema, el **F1-Score** fue considerado la métrica principal de comparación.
- El modelo Ensemble presentó el mejor equilibrio entre Precision, Recall, F1-Score y ROC-AUC, convirtiéndose en la alternativa más adecuada para aplicaciones de evaluación crediticia.

# 11. Conclusiones

- La correcta preparación de los datos, incluyendo la limpieza, codificación de variables, escalamiento y aplicación de SMOTE, mejoró significativamente la capacidad de los modelos para identificar la clase minoritaria (>50K).

- La comparación entre Regresión Logística, Árbol de Decisión, Random Forest, Bagging Classifier y Gradient Boosting evidenció que ningún algoritmo domina simultáneamente todas las métricas de evaluación, por lo que la selección del modelo debe realizarse mediante un análisis integral.

- La utilización conjunta de Accuracy, Precision, Recall, F1-Score y ROC-AUC permitió evaluar el desempeño de los modelos de forma más completa, evitando tomar decisiones basadas únicamente en la Accuracy.

- La optimización mediante Grid Search incrementó el rendimiento de los modelos basados en árboles, obteniendo mejores configuraciones de hiperparámetros y una mayor capacidad de generalización respecto a los modelos base.

- La validación cruzada estratificada confirmó que los modelos presentan un comportamiento estable y consistente, reduciendo el riesgo de sobreajuste y demostrando una buena capacidad para generalizar sobre nuevos datos.

- El análisis de importancia de variables permitió identificar que características como estado civil, edad, nivel educativo, ganancias de capital y horas trabajadas tienen la mayor influencia sobre la predicción del nivel de ingresos, aportando interpretabilidad al modelo.

- Las matrices de confusión y las curvas ROC permitieron analizar de forma detallada los aciertos y errores de cada algoritmo, facilitando una mejor comprensión de su capacidad para distinguir entre ambas clases.

- El modelo Ensemble basado en Voting Classifier logró el mejor equilibrio entre Precision, Recall, F1-Score y ROC-AUC al combinar las fortalezas de Random Forest y Gradient Boosting, obteniendo el desempeño global más robusto del proyecto.

- Debido al desbalance presente en el conjunto de datos, el F1-Score se confirmó como la métrica más adecuada para seleccionar el modelo final, al equilibrar simultáneamente la precisión y la capacidad de detección de la clase minoritaria.

- En conjunto, el proyecto cumplió satisfactoriamente con el objetivo planteado, desarrollando un modelo predictivo confiable, estable e interpretable, demostrando que la integración de un adecuado preprocesamiento, optimización de hiperparámetros, validación rigurosa y técnicas Ensemble constituye una estrategia efectiva para problemas reales de clasificación supervisada.
"""